# Website details
name: "Code @ arthurnn"
description: "arthurnn's Blog"
email: ""
author: "Arthur Nogueira Neves"
lang: "en"
locale: "en_CA"

# Jekyll
paginate: 10
highlighter: "rouge"
markdown: kramdown
gems: [jekyll-paginate]
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title


# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: "UA-19968368-1"

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"
